description = "Generate GitHub issues"
prompt = """
Let's create github issues (deliverable tasks) that satisfies the '{{args}}'. 
Don't forget to include test file as one of the task's deliverables only if applicable, 
and always use github-issue-creator-skill. 

If the two or more issues generated are related to each other, you MUST create a master (parent) issue and add the generated issues as sub-issues. Usually, with the two or more issues is more likely a task that involves backend and mobile (frontend).
"""
